job: "benchmark"
config:
  name: "benchmark"
  benchmark:
    base_config_file: "config/schnell_config.yaml"
    style_datasets:
      - name: "Baroque"
        metadata_file: "Baroque/metadata.json"
    providers:
      - name: "runpod"
        cost_per_sec: 0.08333
        throughput_ratio: 1.0
      - name: "aws_g5"
        cost_per_sec: 0.03
        throughput_ratio: 0.8
    # Optional: best_params, output_dir, etc.
  output_dir: "outputs/Benchmarks"