job: "cost_benchmark"
config:
  name: "cost_benchmark"
  hardware: "runpod"
  base_config_file: "config/schnell_config.yaml"
  providers:
    - name: "runpod"
      cost_per_sec: 0.08333
      throughput_ratio: 1.0
    - name: "aws_g5"
      cost_per_sec: 0.03
      throughput_ratio: 0.8
  datasets:
    - name: "Baroque"
      metadata_file: "Baroque/metadata.json"
      gt_dir: "Baroque/gt"
      prompts_file: "Baroque/prompts.txt"
      process:
        - type: 'sd_trainer'
          training_folder: "outputs/Cost_Benchmarks/Baroque"
          device: cuda:0
          network:
            type: "lora"
            linear: 16
            linear_alpha: 16
          save:
            dtype: float16
            save_every: 2000
            max_step_saves_to_keep: 4
            push_to_hub: false
          datasets:
            - folder_path: "Baroque"
              caption_ext: "txt"
              caption_dropout_rate: 0.05
              shuffle_tokens: false
              cache_latents_to_disk: true
              resolution: [512, 768, 1024]
          train:
            batch_size: 4
            steps: 1000
            gradient_accumulation_steps: 1
            train_unet: true
            train_text_encoder: false
            gradient_checkpointing: true
            noise_scheduler: "flowmatch"
            optimizer: "adamw8bit"
            lr: 1e-4
            skip_first_sample: true
            disable_sampling: true
            ema_config:
              use_ema: true
              ema_decay: 0.99
  output_dir: "outputs/Cost_Benchmarks"