# Optuna HPO parameters for OptimizeJob2
optuna:
  base_config_file: config/schnell_config.yaml
  dataset_metadata: Baroque/metadata.json  # JSON metadata list
  n_trials: 50          # Number of HPO trials
  timeout: 10800        # Max seconds (3 hours)
  n_folds: 5            # Cross-validation folds
  random_seed: 42       # Reproducibility seed
  n_startup_trials: 5   # Pruner startup
